version: "3"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${PG_PASS}
    volumes:
      - "pgdata:/var/lib/postgresql/data"
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - "minio-data:/data"
    command: ["server", "/data"]

volumes:
  pgdata:
  minio-data:
